<?php

namespace App\Enum;

enum Budget: string
{
  case ADMINISTRATIVE = 'ADMINISTRATIVE';
  case LIBRARY = 'LIBRARY';
  case EXPEDITION_EQUIPEMENT = 'EXPEDITION_EQUIPEMENT';
  case OTHER_EQUIPEMENT = 'OTHER_EQUIPEMENT';
  case WEEKENDS_OUTINGS = 'WEEKENDS_OUTINGS';
}
